// RiskDisclaimer.jsx
// FCA / MiFID II style risk disclosure — displayed once every 30 days.
// Mirrors best practice from regulated trading platforms (IG, Saxo, CMC, etc.)

import { useState, useEffect } from 'react';

const RISK_STATEMENTS = [
  "Trading in leveraged financial instruments including Forex, Commodities, CFDs and related products carries a high level of risk and may not be suitable for all investors.",
  "Past performance is not indicative of future results. The value of investments and the income from them can fall as well as rise, and investors may get back less than they originally invested.",
  "This software is a technology tool designed to assist with trade analysis. It does not constitute financial advice, investment recommendations, or a solicitation to trade.",
  "You should ensure that you fully understand the risks involved and, if necessary, seek independent financial advice before using this system.",
  "Retail investors lose money when trading leveraged products. You should only trade with capital you can afford to lose entirely.",
  "The KingIn system accesses live markets via MetaTrader 5 (MT5). All trade execution is the sole responsibility of the account holder.",
];

const RiskDisclaimer = ({ onAccept, onDecline }) => {
  const [checked, setChecked] = useState(false);
  const [countdown, setCountdown] = useState(8);

  // Force minimum reading time before the accept button activates
  useEffect(() => {
    if (countdown > 0) {
      const t = setTimeout(() => setCountdown(c => c - 1), 1000);
      return () => clearTimeout(t);
    }
  }, [countdown]);

  const canAccept = checked && countdown === 0;

  return (
    <div style={s.overlay}>
      <div style={s.modal}>
        {/* Header */}
        <div style={s.header}>
          <div style={s.headerLeft}>
            <span style={s.warningIcon}>⚠</span>
            <div>
              <div style={s.headerTitle}>RISK DISCLOSURE & TERMS OF USE</div>
              <div style={s.headerSub}>Please read carefully before proceeding</div>
            </div>
          </div>
          <div style={s.regulatoryBadge}>IMPORTANT NOTICE</div>
        </div>

        {/* Regulatory preamble */}
        <div style={s.preamble}>
          KingIn Institutional Trading System — Version 1.0
          <br />
          This notice is displayed in accordance with financial regulatory guidance on
          risk disclosure for trading technology platforms.
        </div>

        {/* Risk statements */}
        <div style={s.statementsBox}>
          <div style={s.statementsTitle}>KEY RISK WARNINGS</div>
          {RISK_STATEMENTS.map((stmt, i) => (
            <div key={i} style={s.statement}>
              <span style={s.bullet}>▸</span>
              <span>{stmt}</span>
            </div>
          ))}
        </div>

        {/* Terms & Conditions summary */}
        <div style={s.termsSection}>
          <div style={s.termsTitle}>TERMS OF USE — SUMMARY</div>
          <div style={s.termsGrid}>
            <div style={s.termItem}>
              <span style={s.termLabel}>License</span>
              <span style={s.termValue}>For licensed account holder use only. Redistribution prohibited.</span>
            </div>
            <div style={s.termItem}>
              <span style={s.termLabel}>Liability</span>
              <span style={s.termValue}>KingIn bears no liability for trading losses, system downtime, or incorrect signal generation.</span>
            </div>
            <div style={s.termItem}>
              <span style={s.termLabel}>Data</span>
              <span style={s.termValue}>Market data is provided by your broker via MT5. Accuracy is not guaranteed by this software.</span>
            </div>
            <div style={s.termItem}>
              <span style={s.termLabel}>Regulation</span>
              <span style={s.termValue}>This system does not hold any financial services license. It is a technology tool only.</span>
            </div>
            <div style={s.termItem}>
              <span style={s.termLabel}>No Advice</span>
              <span style={s.termValue}>No content generated by this system constitutes financial, investment, legal or tax advice.</span>
            </div>
            <div style={s.termItem}>
              <span style={s.termLabel}>Acceptance</span>
              <span style={s.termValue}>Continued use constitutes acceptance of these terms. Review is required every 30 days.</span>
            </div>
          </div>
        </div>

        {/* Confirmation */}
        <div style={s.confirmSection}>
          <label style={s.checkLabel}>
            <input
              type="checkbox"
              style={s.checkbox}
              checked={checked}
              onChange={e => setChecked(e.target.checked)}
            />
            <span>
              I confirm that I have read, understood, and agree to the Risk Disclosure and Terms of Use above.
              I acknowledge that trading involves significant risk of loss.
            </span>
          </label>
        </div>

        {/* Actions */}
        <div style={s.actions}>
          <button
            style={{ ...s.btnDecline }}
            onClick={onDecline}
          >
            EXIT APPLICATION
          </button>

          <div style={s.acceptGroup}>
            {countdown > 0 && (
              <span style={s.countdown}>
                Please read — {countdown}s remaining
              </span>
            )}
            <button
              style={{
                ...s.btnAccept,
                opacity: canAccept ? 1 : 0.35,
                cursor: canAccept ? 'pointer' : 'not-allowed',
              }}
              onClick={canAccept ? onAccept : undefined}
              disabled={!canAccept}
            >
              I UNDERSTAND — CONTINUE
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

const s = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0, 0, 0, 0.96)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    zIndex: 9999,
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    padding: '20px',
  },
  modal: {
    width: '100%', maxWidth: '760px',
    maxHeight: '90vh', overflowY: 'auto',
    background: '#0A0D14',
    border: '1px solid #FF8C00',
    borderRadius: '8px',
    boxShadow: '0 0 60px rgba(255, 140, 0, 0.15)',
    display: 'flex', flexDirection: 'column',
  },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '20px 24px',
    background: 'rgba(255, 140, 0, 0.08)',
    borderBottom: '1px solid rgba(255, 140, 0, 0.3)',
  },
  headerLeft: {
    display: 'flex', alignItems: 'center', gap: '14px',
  },
  warningIcon: {
    fontSize: '28px', color: '#FF8C00', lineHeight: 1,
  },
  headerTitle: {
    fontSize: '15px', fontWeight: 700, color: '#FF8C00',
    letterSpacing: '2px',
  },
  headerSub: {
    fontSize: '11px', color: '#8899AA', marginTop: '3px',
    letterSpacing: '0.5px',
  },
  regulatoryBadge: {
    fontSize: '10px', fontWeight: 700, color: '#FF4444',
    border: '1px solid #FF4444', borderRadius: '3px',
    padding: '4px 8px', letterSpacing: '1px',
  },
  preamble: {
    padding: '14px 24px',
    fontSize: '11px', color: '#8899AA',
    lineHeight: '1.6',
    borderBottom: '1px solid #111B2A',
  },
  statementsBox: {
    padding: '20px 24px',
    borderBottom: '1px solid #111B2A',
  },
  statementsTitle: {
    fontSize: '10px', fontWeight: 700, color: '#FF8C00',
    letterSpacing: '2px', marginBottom: '14px',
  },
  statement: {
    display: 'flex', gap: '10px',
    fontSize: '12px', color: '#BCC8D4',
    lineHeight: '1.6', marginBottom: '10px',
    alignItems: 'flex-start',
  },
  bullet: {
    color: '#FF8C00', flexShrink: 0, marginTop: '2px', fontSize: '10px',
  },
  termsSection: {
    padding: '20px 24px',
    borderBottom: '1px solid #111B2A',
  },
  termsTitle: {
    fontSize: '10px', fontWeight: 700, color: '#00C8F0',
    letterSpacing: '2px', marginBottom: '14px',
  },
  termsGrid: {
    display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px',
  },
  termItem: {
    background: '#0F1420', borderRadius: '4px',
    padding: '10px 12px', border: '1px solid #1C2333',
    display: 'flex', flexDirection: 'column', gap: '4px',
  },
  termLabel: {
    fontSize: '10px', fontWeight: 700, color: '#556677',
    letterSpacing: '1px', textTransform: 'uppercase',
  },
  termValue: {
    fontSize: '11px', color: '#9AABB8', lineHeight: '1.5',
  },
  confirmSection: {
    padding: '18px 24px',
    borderBottom: '1px solid #111B2A',
    background: 'rgba(0, 200, 240, 0.03)',
  },
  checkLabel: {
    display: 'flex', alignItems: 'flex-start', gap: '12px',
    cursor: 'pointer', fontSize: '12px', color: '#BCC8D4', lineHeight: '1.6',
  },
  checkbox: {
    width: '16px', height: '16px', flexShrink: 0, marginTop: '2px', cursor: 'pointer',
    accentColor: '#00C8F0',
  },
  actions: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '16px 24px', gap: '12px',
  },
  btnDecline: {
    padding: '10px 20px',
    background: 'transparent', border: '1px solid #334',
    color: '#556677', borderRadius: '4px',
    fontSize: '11px', fontWeight: 700, letterSpacing: '1px',
    cursor: 'pointer',
  },
  acceptGroup: {
    display: 'flex', alignItems: 'center', gap: '14px',
  },
  countdown: {
    fontSize: '11px', color: '#FF8C00', letterSpacing: '0.5px',
  },
  btnAccept: {
    padding: '10px 24px',
    background: '#00C8F0', border: 'none',
    color: '#000', borderRadius: '4px',
    fontSize: '11px', fontWeight: 700, letterSpacing: '1px',
    transition: 'opacity 0.3s',
  },
};

export default RiskDisclaimer;
